### ISSUE TITLE
Trunk doesn't compile

### ISSUE THREAD

**Issue by dkmorb** [HolyCityAudio/SpinCAD-Designer#2]
After resolve external jar issues, project in trunk doesn't compile

ERROR LIST
AbsaCADBlock cannot be resolved to a type	standardMenu.java	
ChorusCADBlock cannot be resolved to a type	standardMenu.java	
ExpCADBlock cannot be resolved to a type	standardMenu.java	
FlangerCADBlock cannot be resolved to a type	standardMenu.java	
Glitch_shiftCADBlock cannot be resolved to a type	standardMenu.java	
LogCADBlock cannot be resolved to a type	standardMenu.java	
Phase_InvertCADBlock cannot be resolved to a type	standardMenu.java	
Pitch_shift_testCADBlock cannot be resolved to a type	standardMenu.java	
ramp_lfo_testControlPanel cannot be resolved to a type	ramp_lfo_testCADBlock.java	
ramp_lfo_testControlPanel cannot be resolved to a type	ramp_lfo_testCADBlock.java	
ramp_lfo_testControlPanel cannot be resolved to a type	ramp_lfo_testCADBlock.java	
ramp_lfo_testControlPanel cannot be resolved to a type	ramp_lfo_testCADBlock.java	
ramp_lfo_testControlPanel cannot be resolved to a type	ramp_lfo_testCADBlock.java	
SampleHoldCADBlock cannot be resolved to a type	standardMenu.java	
servoCADBlock cannot be resolved to a type	standardMenu.java	
sixtapCADBlock cannot be resolved to a type	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.AbsaCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.ChorusCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.ExpCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.FlangerCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.Glitch_shiftCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.LogCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.Phase_InvertCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.Pitch_shift_testCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.SampleHoldCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.servoCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.CADBlocks.sixtapCADBlock cannot be resolved	standardMenu.java	
The import com.holycityaudio.SpinCAD.ControlPanel.ramp_lfo_testControlPanel cannot be resolved	ramp_lfo_testCADBlock.java

**Comment by Digital-Larry** [comment]
Thanks for bringing this to my attention.  I'm currently having some difficulty with adding copied/pasted source files from within Eclipse to Git.  All of the files you listed are in this category.  I'll try to solve it this morning.  Thanks for your interest in SpinCAD Designer!

**Comment by Digital-Larry** [comment]
OK please try it now.

**Comment by dkmorb** [comment]
Hey Larry,
I think you have to commit files on the server, after adding the files to repo.

**Comment by Digital-Larry** [comment]
I see them directly on github!  Make sure you're pulling from commit:

d4445c5225e0fa629b06331e40b9ac82fe846d92

**Comment by dkmorb** [comment]
Time to add ControlPanels :-)

AbsaControlPanel cannot be resolved to a type	
ChorusControlPanel cannot be resolved to a type	
ExpControlPanel cannot be resolved to a type	
FlangerControlPanel cannot be resolved to a type	
Glitch_shiftControlPanel cannot be resolved to a type	
LogControlPanel cannot be resolved to a type	
PatternGeneratorControlPanel cannot be resolved to a type	
SampleHoldControlPanel cannot be resolved to a type

**Comment by Digital-Larry** [comment]
OK!  Here you go.  Git does some kinda weird things inside Eclipse that I did not plan for.

Take commit:  d28d9f6e3c3ec3873e985bfd34dcf12d4f62b854

**Comment by dkmorb** [comment]
ok...just a problem with expanderSomeThing ...I deleted that file and now it works!!!

**Comment by Digital-Larry** [comment]
great!
