### ISSUE TITLE
Error in Generating Hex File

### ISSUE THREAD

**Issue by ozhewett** [HolyCityAudio/SpinCAD-Designer#44]
Hey!
HEX file from the bank doesn't format correctly. This is a photo of the generated HEX file from a simple chorus patch.

<img width="1370" alt="Screen Shot 2022-09-05 at 11 23 08 AM" src="https://user-images.githubusercontent.com/67621377/188480998-443000b0-f46a-45d7-b0eb-75b8487e75f7.png">

**Comment by Digital-Larry** [comment]
What's the actual problem?  Are you unable to use the HEX file?

**Comment by ozhewett** [comment]
The EEPROM burner im using expects code like this:

`const unsigned char ROM_00[] PROGMEM = {
0x40,0x00,0x02,0x84,
0x00,0x00,0x00,0x09,
0x80,0x00,0x00,0x0D,
0x80,0x00,0x00,0x0D,
0x00,0x10,0x04,0x25,
0x00,0x00,0x04,0x26,
0x00,0x00,0x00,0x0D,
0x00,0x0C,0x02,0xA4,
0x40,0x00,0x04,0x64,
0x00,0x00,0x04,0xA6,
0x00,0x65,0x02,0xA4,
0x7E,0x7E,0x04,0xA4,
0x40,0x00,0x04,0x84,
0x00,0x00,0x04,0x66,
0x00,0x32,0x02,0xA4,
0xC0,0xB6,0x04,0xA4,
0x00,0x00,0x04,0x86,
...`
How do you burn it using that format?

**Comment by ozhewett** [comment]
Oh I see, It just requires converting UTF-8 to HEX! Thanks

**Comment by Digital-Larry** [comment]
The generated hex files work fine with my PICKit 2 clone and PK2CMD.exe.  So, I think they are "right".  Maybe they need a format conversion?

**Comment by ozhewett** [comment]
The problem was outputting a C header file, which I believe is only possible in SpinASM. I got around this by formatting it according to this photo, and adding a ",0x" in front of each of the data byte pairs

**Comment by Digital-Larry** [comment]
Yeah, SpinCAD doesn't have that option.  You can also export patches to Spin ASM and then use the Spin IDE for that.  Or, you could contribute a pull request against SpinCAD adding the feature!  Know any Java?
