### ISSUE TITLE
File-Open, and scrollable workarea fixes

### ISSUE THREAD

**Issue by sreichholf** [HolyCityAudio/SpinCAD-Designer#5]
Hey,

i have fixed some issues that occured when any of the "open" dialogs was canceled and fixed up the work-area scroll thing a bit (with a 3840x2560 working area for now).
There was also an issue with setting the theme that I've fixed.

I also added commons-io / elmgen for easy bulding/running.
You can have a look at my changes here

https://github.com/sreichholf/SpinCAD-Designer

I didn't want to open a pull-request out of nowhere.
So would you like me to open pull-requests?
For all of the commits?
Only for some?

I could split them into several pull requests, it's all up to what you'd prefer :)

**Comment by Digital-Larry** [comment]
Hi, Can you please split them into individual pull requests?  Thanks a
lot!

DL

**Comment by sreichholf** [comment]
Sure. Done.
