### ISSUE TITLE
What is "Open Hex" supposed to do?

### ISSUE THREAD

**Issue by jberryman** [HolyCityAudio/SpinCAD-Designer#9]
I'm new to SpinCAD Designer and just getting oriented. I was curious to see what would happen if I tried giving SpinCAD an existing patch (not created with SpinCAD); I hoped it might (but didn't expect it to) display a visual representation of the patch for editing.

"File > Open Hex" didn't throw any errors, but nothing seemed to happen. What is "Open Hex" for?

Also where would I find documentation or a user manual?

**Comment by Digital-Larry** [comment]
"Open Hex" allows you to include a hex which came from somewhere else into a bank.  It will only take the first 128 instructions out of the hex file, so the patch you want needs to be the first one.  If you had a hex file which itself contains 8 patches and you wanted to include #5, then you'll need to manually trim out the lines before that one.

The function just copies the bytes from the supplied hex back out to the new hex file only when you export a hex file, along with modified addressing if needed (depending on the position of the patch within the bank).

Yeah, wouldn't it be great if I could compose a patch from a hex file.  It didn't figure into my approach when I was actively developing the program so I didn't bother.

There's no single manual document, however there are lots of threads in the forum which talk about doing various things.  Some of these have been submitted by end users.  If you have a specific question I will try to answer it at the forum.  http://holycityaudio.com/forum

**Comment by jberryman** [comment]
Thanks, and thanks for your work on SpinCAD!
